//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoFuture.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoFuture.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([a-zA-Z\*]+)\s{1,2}([a-zA-Z0-9_]+)\:\:([a-zA-Z0-9_]+)\x28([a-zA-Z0-9_\,\&amp;\*\s]*)\x29$.
        /// </summary>
        internal static string CppClassMember {
            get {
                return ResourceManager.GetString("CppClassMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(public|protected|internal|private).*\sclass\s.*([a-z0-9A-Z_\&lt;\&gt;,\s\:\,])*[^\(\)]\s*$.
        /// </summary>
        internal static string CsClass {
            get {
                return ResourceManager.GetString("CsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*[^\Wif\W|\Wfor\W|\Wforeach\W]\s*\([a-z0-9A-Z_,\s]*\)\s*$.
        /// </summary>
        internal static string CsClassMember {
            get {
                return ResourceManager.GetString("CsClassMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(public|protected|internal|private)\s*([a-z0-9A-Z_\&lt;\&gt;,\s])*\([a-z0-9A-Z_,\s\&lt;\&gt;]*\)\s*$.
        /// </summary>
        internal static string CsFunction {
            get {
                return ResourceManager.GetString("CsFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((\&quot;.*\&lt;.*\&gt;.*\&quot;)|(\&apos;.*\&lt;.*\&gt;.*\&apos;)).
        /// </summary>
        internal static string EmbeddedHtml {
            get {
                return ResourceManager.GetString("EmbeddedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}.
        /// </summary>
        internal static string IPv4 {
            get {
                return ResourceManager.GetString("IPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\s*function\W.
        /// </summary>
        internal static string JsFunction {
            get {
                return ResourceManager.GetString("JsFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (January|February|March|April|May|June|July|August|September|October|November|December)\W[1-3][0-9]\x2C?\W[0-9]{1,4}.
        /// </summary>
        internal static string LongDate {
            get {
                return ResourceManager.GetString("LongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((\d{3})|(\(\d{3}\)))?[\s|-]?\d{3}[\s|-]?\d{4}$.
        /// </summary>
        internal static string PhoneNumber01 {
            get {
                return ResourceManager.GetString("PhoneNumber01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\x28]*[1-9][0-9]{2}[\x2d\x20\x29\x2e]*[1-9][0-9]{2}[\x2d\x20\x2e]*[0-9]{4}$.
        /// </summary>
        internal static string PhoneNumber02 {
            get {
                return ResourceManager.GetString("PhoneNumber02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([\x0A\x0D]|[\x0D]|\W)?[Ss][Ee][Ll][Ee][Cc][Tt]([\x0A\x0D]|[\x0D]|\W)?([a-zA-Z0-9_\x2c\x5b\x5d\x2e\W]*?)([\x0A\x0D]|[\x0D]|\W)[Ff][Rr][Oo][Mm].
        /// </summary>
        internal static string SqlSelectValues {
            get {
                return ResourceManager.GetString("SqlSelectValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^\(]+[Ff][Rr][Oo][Mm]\s+(([a-zA-Z_0-9]+|\x5b[a-zA-Z_0-9\x2e]+\x5d)\x2e)?([a-zA-Z_0-9]+|\x5b[a-zA-Z_0-9\x2e]+\x5d)\x2e[a-zA-Z_0-9]+.*.
        /// </summary>
        internal static string SqlServerTableName {
            get {
                return ResourceManager.GetString("SqlServerTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\D?)(\d{3})(\D?)(\d{2})(\D?)(\d{4}$).
        /// </summary>
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\\\?\*\,\(\$\|\+]+.
        /// </summary>
        internal static string StringIsRegex {
            get {
                return ResourceManager.GetString("StringIsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((\&quot;([\x3a\x3d\x5b\x5d\x3f\x2f\x5c\x2e\x2c\x23\x21\x40\x24\x25\x5e\x26\x2a\x28\x29\x2d\x5f\x2b\x7b\x7d\x7c\&apos;a-z0-9\s]+)\&quot;))|((\&apos;([\x3a\x3d\x5b\x5d\x3f\x2f\x5c\x2e\x2c\x23\x21\x40\x24\x25\x5e\x26\x2a\x28\x29\x2d\x5f\x2b\x7b\x7d\x7c\&quot;a-z0-9\s]+)\&apos;)).
        /// </summary>
        internal static string StringLiteral {
            get {
                return ResourceManager.GetString("StringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\d{1,2})(\D?)(\d{1,2})(\D?)(\d{2}$|\d{4}$)(\s*)(AM|am|PM|pm|a|p|A|P).
        /// </summary>
        internal static string TimeValue {
            get {
                return ResourceManager.GetString("TimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?.
        /// </summary>
        internal static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((mailto\:|(news|(ht|f)tp(s?))\://)|(www))+.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (([a-zA-Z0-9\-])+\.)?([a-zA-Z0-9\-])+\.(com|net|org|edu|gov|mil).
        /// </summary>
        internal static string UrlClassicAmerican {
            get {
                return ResourceManager.GetString("UrlClassicAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\$]|[\$]\s)*[1-9](([\,]*[0-9]{3})|([0-9]))+([\.][0-9]{2})*$.
        /// </summary>
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9]{5}([\-][0-9]{4})*$.
        /// </summary>
        internal static string UsZipcode {
            get {
                return ResourceManager.GetString("UsZipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\Wfunction\W|\Wsub\W|\Wproperty\W).
        /// </summary>
        internal static string VbClassMember {
            get {
                return ResourceManager.GetString("VbClassMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([A-Z]\x3a\x5c|\x5c\x5c)[^\x22\x3c\x3e\x7c\x5c]+?\x5c.
        /// </summary>
        internal static string WindowsRootedPath {
            get {
                return ResourceManager.GetString("WindowsRootedPath", resourceCulture);
            }
        }
    }
}
