//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Projects\31g\trunk\Code\NoFuture\Antlr\Grammers\DotNetIlTypeName.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace NoFuture.Antlr.DotNetIlTypeName
{

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDotNetIlTypeNameListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public partial class DotNetIlTypeNameBaseListener : IDotNetIlTypeNameListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.utPrius"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUtPrius([NotNull] DotNetIlTypeNameParser.UtPriusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.utPrius"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUtPrius([NotNull] DotNetIlTypeNameParser.UtPriusContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotNetGenericName([NotNull] DotNetIlTypeNameParser.DotNetGenericNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotNetGenericName([NotNull] DotNetIlTypeNameParser.DotNetGenericNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotNetGenericArg([NotNull] DotNetIlTypeNameParser.DotNetGenericArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotNetGenericArg([NotNull] DotNetIlTypeNameParser.DotNetGenericArgContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotNetAsmTypeName([NotNull] DotNetIlTypeNameParser.DotNetAsmTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotNetAsmTypeName([NotNull] DotNetIlTypeNameParser.DotNetAsmTypeNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotNetAsmName([NotNull] DotNetIlTypeNameParser.DotNetAsmNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotNetAsmName([NotNull] DotNetIlTypeNameParser.DotNetAsmNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotNetName([NotNull] DotNetIlTypeNameParser.DotNetNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotNetName([NotNull] DotNetIlTypeNameParser.DotNetNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsmVersion([NotNull] DotNetIlTypeNameParser.AsmVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsmVersion([NotNull] DotNetIlTypeNameParser.AsmVersionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmCulture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsmCulture([NotNull] DotNetIlTypeNameParser.AsmCultureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmCulture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsmCulture([NotNull] DotNetIlTypeNameParser.AsmCultureContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmPubToken"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsmPubToken([NotNull] DotNetIlTypeNameParser.AsmPubTokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmPubToken"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsmPubToken([NotNull] DotNetIlTypeNameParser.AsmPubTokenContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmProArch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsmProArch([NotNull] DotNetIlTypeNameParser.AsmProArchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmProArch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsmProArch([NotNull] DotNetIlTypeNameParser.AsmProArchContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.tokenValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTokenValue([NotNull] DotNetIlTypeNameParser.TokenValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.tokenValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTokenValue([NotNull] DotNetIlTypeNameParser.TokenValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace NoFuture.Antlr.DotNetIlTypeName
