//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Projects\31g\trunk\Code\NoFuture\Antlr\Grammers\DotNetIlTypeName.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace NoFuture.Antlr.DotNetIlTypeName
{
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DotNetIlTypeNameParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IDotNetIlTypeNameListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.utPrius"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUtPrius([NotNull] DotNetIlTypeNameParser.UtPriusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.utPrius"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUtPrius([NotNull] DotNetIlTypeNameParser.UtPriusContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotNetGenericName([NotNull] DotNetIlTypeNameParser.DotNetGenericNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotNetGenericName([NotNull] DotNetIlTypeNameParser.DotNetGenericNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotNetGenericArg([NotNull] DotNetIlTypeNameParser.DotNetGenericArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetGenericArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotNetGenericArg([NotNull] DotNetIlTypeNameParser.DotNetGenericArgContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotNetAsmTypeName([NotNull] DotNetIlTypeNameParser.DotNetAsmTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotNetAsmTypeName([NotNull] DotNetIlTypeNameParser.DotNetAsmTypeNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotNetAsmName([NotNull] DotNetIlTypeNameParser.DotNetAsmNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetAsmName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotNetAsmName([NotNull] DotNetIlTypeNameParser.DotNetAsmNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotNetName([NotNull] DotNetIlTypeNameParser.DotNetNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.dotNetName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotNetName([NotNull] DotNetIlTypeNameParser.DotNetNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmVersion([NotNull] DotNetIlTypeNameParser.AsmVersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmVersion([NotNull] DotNetIlTypeNameParser.AsmVersionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmCulture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmCulture([NotNull] DotNetIlTypeNameParser.AsmCultureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmCulture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmCulture([NotNull] DotNetIlTypeNameParser.AsmCultureContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmPubToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmPubToken([NotNull] DotNetIlTypeNameParser.AsmPubTokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmPubToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmPubToken([NotNull] DotNetIlTypeNameParser.AsmPubTokenContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.asmProArch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmProArch([NotNull] DotNetIlTypeNameParser.AsmProArchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.asmProArch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmProArch([NotNull] DotNetIlTypeNameParser.AsmProArchContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DotNetIlTypeNameParser.tokenValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokenValue([NotNull] DotNetIlTypeNameParser.TokenValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DotNetIlTypeNameParser.tokenValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokenValue([NotNull] DotNetIlTypeNameParser.TokenValueContext context);
}
} // namespace NoFuture.Antlr.DotNetIlTypeName
